# Generated by Django 5.2.8 on 2025-12-23 20:23

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "new_password_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "new_password_code_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.User.profile_upload_path,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verified_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "financial_targets",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nothing", "دسته بندی نشده"),
                            ("salary", "حقوق"),
                            ("food", "خوراک"),
                            ("clothes", "پوشاک"),
                            ("transportation", "حمل و نقل"),
                            ("hobby", "سرگرمی و تفریح"),
                            ("health", "سلامتی"),
                            ("investment", "سرمایه گذاری"),
                            ("loan", "وام"),
                            ("rent", "اجاره"),
                            ("bill", "قبض ها"),
                        ],
                        default="nothing",
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "درآمد"), ("outcome", "هزینه")],
                        default="income",
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=250, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="main.user",
                    ),
                ),
            ],
        ),
    ]
