# Generated by Django 5.2.8 on 2026-04-30 16:52

import django.db.models.deletion
import django.utils.timezone
import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=panel.models.get_profile_upload_path)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_targets', to='panel.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nothing', 'دسته بندی نشده'), ('salary', 'حقوق'), ('food', 'خوراک'), ('clothes', 'پوشاک'), ('transportation', 'حمل و نقل'), ('hobby', 'سرگرمی و تفریح'), ('health', 'سلامتی'), ('investment', 'سرمایه گذاری'), ('loan', 'وام'), ('rent', 'اجاره'), ('bill', 'قبض ها')], default='nothing', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('income', 'درآمد'), ('outcome', 'هزینه')], default='income', max_length=10)),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
